version: '3'
services:
  db:
    image: mongo:latest
    volumes:
      - db:/data/db
      
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - ecommerce_api
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  ecommerce_api:
    build: 
      context: "./server/"
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "4000:4000"
  
  # ecommerce_client:
  #   build: 
  #     context: "./client/"
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - ecommerce_api
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped

  redis: 
    image: redis:6.2.12-alpine
    depends_on:
      - db
volumes:
  db: 

