version: '2'
services:
  ecommerce_api:
    build: 
      context: "./server"
      args:
        - NODE_ENV=production
    volumes:
      - ./server/images:/ecommerce/server/images
    command: node src/app.js
  ecommerce_client:
    build: 
      context: "./client"
      args:
        - NODE_ENV=production
    command: >
        sh -c "npm run build && npm run start"
volumes:
  images: